server:
  port: 8764

spring:
  application:
    name: service-miya
  zipkin:
    base-url: http://localhost:9411  #增加zipkin服务追踪配置

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
